// "Learn faster" encyclopedia: evidence-based practice principles (in our own words, with sources),
// each with a picture and how to apply it on this site, plus every trick from every lesson, searchable.
const SRC={
  slow:["Allingham & Wöllner (2022): التمرين البطيء عند العازفين","https://journals.sagepub.com/doi/10.1177/03057356211073481"],
  inter:["Carter & Grahn (2016): الخلط مقابل التكرار بالموسيقى","https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4989027/"],
  space:["التمرين الموزّع وتثبيت الذاكرة عند العازفين","https://www.researchgate.net/publication/258156119_Distributed_Practice_and_Procedural_Memory_Consolidation_in_Musicians'_Skill_Learning"],
  gebrian:["Molly Gebrian: Learn Faster, Perform Better (Oxford 2024)","https://global.oup.com/academic/product/learn-faster-perform-better-9780197680063"],
  gebrianT:["Molly Gebrian: قائمة استراتيجيات التمرين (PDF)","https://mollygebrian.squarespace.com/s/Gebrian-Appendix-A.pdf"],
  mental:["Bernardi وآخرين (2013): التمرين الذهني عند العازفين","https://www.frontiersin.org/journals/human-neuroscience/articles/10.3389/fnhum.2013.00451/full"],
  delib:["Passarotto وآخرين (2022): التمرين المقصود بالموسيقى","https://journals.sagepub.com/doi/full/10.1177/03057356211065172"],
  chunk:["Classical Guitar Corner: التقسيم لمقاطع","https://www.classicalguitarcorner.com/chunking-in-guitar-practice/"],
  six:["Six String Journal: شو اللي العلم بيدعمه بتمرين الكلاسيك","https://sixstringjournal.com/2026/02/12/practicing-classical-guitar-smarter-what-science-actually-supports/"],
  mway:["Musician's Way: التمرين المتنوّع والموزّع والمخلوط","https://www.musiciansway.com/blog/2017/10/varied-distributed-and-interleaved-practice/"],
  tone:["tonebase: كيف تتمرّن على الكلاسيك","https://www.tonebase.co/guitar-blog-posts/how-to-practice-classical-guitar"],
  memo:["Bulletproof Musician: الحفظ مع Molly Gebrian","https://bulletproofmusician.com/molly-gebrian-on-efficient-effective-and-reliable-memorization-strategies-for-musicians/"],
  bw:["Bradford Werner: كيف تنظّم جلسة التمرين","https://www.thisisclassicalguitar.com/lesson-how-to-practice-music-and-organize-your-practice-session/"],
};
const box=(x,y,w,h,c,t,tc="#121826")=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="6" fill="${c}"/>${t?`<text x="${x+w/2}" y="${y+h/2+5}" text-anchor="middle" font-size="13" font-weight="700" fill="${tc}">${t}</text>`:""}`;
const LP={
  slow:`<svg viewBox="0 0 320 160"><text x="160" y="20" text-anchor="middle" font-size="13" fill="#A3AABB">السرعة (bpm) على أيام</text>${[50,55,60,65,70,80,90,100].map((v,i)=>box(24+i*36,140-v,26,v,i<4?"#4FB3A9":"#E6B04B")+`<text x="${37+i*36}" y="155" text-anchor="middle" font-size="10" fill="#A3AABB">${i+1}</text>`).join("")}</svg>`,
  chunk:`<svg viewBox="0 0 320 160"><text x="160" y="22" text-anchor="middle" font-size="13" fill="#A3AABB">مقطوعة = قطع صغيرة</text>${[0,1,2,3,4,5].map(i=>box(20+i*48,50,42,40,i%2?"#243049":"#2C3752",`${i+1}`,"#F1EBDD")).join("")}${box(20,110,90,30,"#E6B04B","1+2")}${box(116,110,90,30,"#E6B04B","3+4")}${box(212,110,90,30,"#E6B04B","5+6")}</svg>`,
  space:`<svg viewBox="0 0 320 160"><text x="80" y="22" text-anchor="middle" font-size="13" fill="#FF7A66">✗ ساعتين مرة</text><text x="240" y="22" text-anchor="middle" font-size="13" fill="#5FD39A">✓ ٢٠ دقيقة كل يوم</text>${[0,1,2,3,4,5,6].map(i=>box(12+i*20,40,16,100,i===5?"#FF7A66":"#243049")).join("")}${[0,1,2,3,4,5,6].map(i=>box(172+i*20,110,16,30,"#5FD39A")).join("")}</svg>`,
  inter:`<svg viewBox="0 0 320 160"><text x="160" y="20" text-anchor="middle" font-size="13" fill="#A3AABB">فوق: تكرار · تحت: خلط (أحسن للمدى الطويل)</text>${"AAABBBCCC".split("").map((c,i)=>box(14+i*33,36,28,40,c==="A"?"#4FB3A9":c==="B"?"#6F9CFF":"#C58BFF",c)).join("")}${"ABCBCACAB".split("").map((c,i)=>box(14+i*33,96,28,40,c==="A"?"#4FB3A9":c==="B"?"#6F9CFF":"#C58BFF",c)).join("")}</svg>`,
  sleep:`<svg viewBox="0 0 320 160"><path d="M120 30 A50 50 0 1 0 170 110 A40 40 0 1 1 120 30Z" fill="#E6B04B"/><text x="230" y="60" font-size="22" fill="#F1EBDD" font-family="IBM Plex Mono,monospace">z</text><text x="250" y="42" font-size="28" fill="#F1EBDD" font-family="IBM Plex Mono,monospace">Z</text><text x="160" y="150" text-anchor="middle" font-size="13" fill="#A3AABB">الدماغ بيثبّت اللي تعلّمته وانت نايم</text></svg>`,
  delib:`<svg viewBox="0 0 320 160">${[60,44,28,12].map((r,i)=>`<circle cx="160" cy="84" r="${r}" fill="${i%2?"#243049":"#2C3752"}"/>`).join("")}<circle cx="160" cy="84" r="6" fill="#E6B04B"/><path d="M250 30 L168 80" stroke="#E6B04B" stroke-width="4" stroke-linecap="round"/><text x="160" y="156" text-anchor="middle" font-size="13" fill="#A3AABB">ركّز على النقطة الضعيفة بس</text></svg>`,
  mental:`<svg viewBox="0 0 320 160"><ellipse cx="160" cy="80" rx="80" ry="58" fill="#243049" stroke="#6F9CFF" stroke-width="3"/><path d="M120 70 q20 -30 40 0 q20 30 40 0" fill="none" stroke="#6F9CFF" stroke-width="3"/><g fill="#E6B04B"><circle cx="140" cy="102" r="6"/><rect x="145" y="72" width="3" height="30"/><circle cx="178" cy="98" r="6"/><rect x="183" y="68" width="3" height="30"/></g><text x="160" y="154" text-anchor="middle" font-size="13" fill="#A3AABB">اعزفها بخيالك قبل ما تنام</text></svg>`,
  record:`<svg viewBox="0 0 320 160"><rect x="90" y="40" width="120" height="80" rx="12" fill="#2C3752"/><circle cx="150" cy="80" r="26" fill="#121826" stroke="#E6B04B" stroke-width="5"/><rect x="210" y="60" width="30" height="40" rx="4" fill="#2C3752"/><circle cx="110" cy="54" r="6" fill="#FF7A66"/><text x="160" y="150" text-anchor="middle" font-size="13" fill="#A3AABB">فيديو كل أسبوع، وقارن</text></svg>`,
  rhythm:`<svg viewBox="0 0 320 160"><text x="160" y="20" text-anchor="middle" font-size="13" fill="#A3AABB">نفس النغمات بإيقاعات مختلفة</text>${[[40,20,40,20,40,20],[20,40,20,40,20,40],[30,30,30,30,30,30]].map((row,r)=>{let x=20;return row.map(w=>{const s=box(x,36+r*40,w*1.9-4,28,["#4FB3A9","#E6B04B","#6F9CFF"][r]);x+=w*1.9;return s}).join("")}).join("")}</svg>`,
  recall:`<svg viewBox="0 0 320 160"><rect x="40" y="40" width="100" height="80" rx="8" fill="#2C3752"/><path d="M40 40 L140 120 M140 40 L40 120" stroke="#FF7A66" stroke-width="4"/><text x="90" y="140" text-anchor="middle" font-size="12" fill="#A3AABB">سكّر النوتة</text><path d="M170 80 h40 M200 70 l12 10 -12 10" stroke="#E6B04B" stroke-width="4" fill="none" stroke-linecap="round"/><ellipse cx="260" cy="80" rx="38" ry="30" fill="#243049" stroke="#5FD39A" stroke-width="3"/><text x="260" y="86" text-anchor="middle" font-size="18" fill="#5FD39A">✓</text><text x="260" y="140" text-anchor="middle" font-size="12" fill="#A3AABB">اعزف من راسك</text></svg>`,
  three:`<svg viewBox="0 0 320 160">${[0,1,2].map(i=>`<circle cx="${90+i*70}" cy="70" r="26" fill="#1F3B30" stroke="#5FD39A" stroke-width="4"/><text x="${90+i*70}" y="78" text-anchor="middle" font-size="22" fill="#5FD39A">✓</text>`).join("")}<text x="160" y="136" text-anchor="middle" font-size="14" fill="#F1EBDD">٣ مرات صح ورا بعض ← +٥ bpm</text></svg>`,
  micro:`<svg viewBox="0 0 320 160"><text x="160" y="20" text-anchor="middle" font-size="13" fill="#A3AABB">تمرّن ٢٥ د، استراحة ٥ د</text>${[0,1,2].map(i=>box(20+i*100,50,70,50,"#4FB3A9","٢٥ د")+(i<2?box(92+i*100,62,24,26,"#E6B04B","٥"):"")).join("")}</svg>`,
};
const PRINCIPLES=[
  {k:"slow",t:"ابدأ بنص السرعة",d:"اشتغل على أي مقطع جديد على نص سرعته تقريباً، لحد ما يطلع نظيف. البطء بيعطي دماغك وقت يرتّب الحركة، وبيقلّل الأغلاط اللي بتثبت غلط. أغلب العازفين المحترفين بيستعملوا هاد الأسلوب أكتر من أي أسلوب ثاني.",how:"بالمدرّب نزّل السرعة لـ 50%، وارفع ٥ بس لما تعزفه نظيف ٣ مرات ورا بعض.",src:[SRC.slow,SRC.tone]},
  {k:"three",t:"قاعدة ٣ مرات صح",d:"ما تسرّع إلا لما تعزف المقطع ٣ مرات صح ورا بعض. مرة وحدة صح ممكن تكون حظ.",how:"استعمل «حدّد مقطع (A–B)» على الجزء الصعب، وعدّ ٣ مرات نظيفة.",src:[SRC.bw]},
  {k:"chunk",t:"قسّم لقطع صغيرة",d:"دماغك بيحمل كمية محدودة بنفس الوقت. قسّم الأغنية لقطع صغيرة (مازورتين)، وتعلّم كل قطعة لحالها، وبعدين اربطهم ببعض. وجرّب تبدأ من الآخر.",how:"بالتاب اللي تحت الجيتار: «حدّد مقطع» على مازورتين، وبعدين كبّر المقطع.",src:[SRC.chunk,SRC.gebrianT]},
  {k:"delib",t:"تمرّن على نقطة الضعف",d:"إنك تعزف الأغنية من أولها لآخرها كل مرة مش تمرين، هاد تكرار للإشي اللي بتعرفه. التمرين الحقيقي إنك تحدّد المكان اللي بتغلط فيه وتشتغل عليه هو بس، بهدف واضح.",how:"اسأل حالك قبل كل جلسة: شو الإشي الوحيد اللي بدي يتحسّن اليوم؟",src:[SRC.delib,SRC.six]},
  {k:"space",t:"شوي كل يوم، مش كتير مرة",d:"الأبحاث بتلاقي إن التمرين الموزّع على أيام بيثبت بالذاكرة أحسن بكتير من نفس الوقت كله بيوم واحد.",how:"صفحة «تمرين اليوم» مبنية على هاد: ٢٥-٣٠ دقيقة كل يوم.",src:[SRC.space,SRC.mway]},
  {k:"inter",t:"اخلط بين المهارات",d:"بدل ما تعزف الإشي نفسه ٣٠ مرة ورا بعض، بدّل بين ٢-٣ مهارات (كورد، أربيج، أغنية). وقت التمرين بيبيّن كأنك أبطأ، بس بتتذكّر أحسن بعد أسابيع.",how:"بتمرين الدقيقة بدّل بين أكتر من زوج كوردات بنفس الجلسة.",src:[SRC.inter,SRC.mway]},
  {k:"micro",t:"استراحات قصيرة",d:"استراحات قصيرة بين المحاولات، واستراحة أطول كل نص ساعة، بتساعد الدماغ يثبّت. والتمرين المتواصل لوقت طويل بيجيب تعب وأغلاط.",how:"بين كل خطوة بتمرين اليوم خذ دقيقة، وهزّ إيديك.",src:[SRC.gebrian]},
  {k:"sleep",t:"النوم جزء من التمرين",d:"وانت نايم الدماغ بينقل اللي تعلّمته من الذاكرة القصيرة للطويلة. عشان هيك كتير مرات الإشي اللي ما زبط اليوم بتلاقيه أسهل بكرة.",how:"تمرّن على المقطع الصعب بالمسا، وجرّبه تاني يوم الصبح.",src:[SRC.gebrian]},
  {k:"mental",t:"التمرين بالخيال",d:"إنك تتخيّل حالك بتعزف (شايف الأصابع وسامع الصوت) بيفعّل نفس مناطق الدماغ جزئياً. أضعف من العزف الحقيقي، بس بيساعد، خصوصاً بالتوقيت وبالحفظ.",how:"شوف المدرّب ودماغك بيقلّد، وبعدين سكّر عيونك وتخيّل الأصابع قبل ما تعزف.",src:[SRC.mental]},
  {k:"rhythm",t:"نوّع الإيقاع للمقطع الصعب",d:"اعزف المقطع السريع بإيقاعات مختلفة (طويل-قصير، قصير-طويل). هيك بتجبر أصابعك تتعلّم الانتقالات بشكل منفصل.",how:"على مقطع أربيج أو سلّم: غيّر الإيقاع كل مرة.",src:[SRC.slow]},
  {k:"recall",t:"اعزف من راسك",d:"إنك تحاول تتذكّر (بدون ما تطلّع على التاب) بيثبّت أقوى من إنك تعيد تقرأ. الغلط وقت المحاولة جزء من التعلّم.",how:"بعد ما تتعلّم مقطع، سكّر التاب وجرّب. وأسئلة «اتأكد» بآخر كل درس مبنية على هاد.",src:[SRC.memo]},
  {k:"record",t:"سجّل حالك",d:"وانت بتعزف ما بتنتبه لإشياء كتير. الفيديو بيورجيك الرسغ، والإبهام، والتوتّر، والإيقاع. وكمان بتشوف قديش تحسّنت.",how:"فيديو قصير كل أسبوع لنفس الأغنية، وقارنهم ببعض.",src:[SRC.tone]},
];
function renderLearn(view){
  const tricks=ALL.map(l=>({l,t:l.trick.replace(/<[^>]+>/g,"")}));
  view.innerHTML=`${crumb("<span>موسوعة التعلّم السريع</span>")}<div class="uh"><span class="tag">موسوعة التعلّم السريع</span><h2>كيف تتعلّم أسرع (والعلم ورا الكلام)</h2><p>١٢ مبدأ من أبحاث التعلّم والموسيقى وتجارب أساتذة الكلاسيك. كل مبدأ إله رسمة، وكيف تطبّقه بالموقع، والمصدر.</p></div>
  <div class="prgrid">${PRINCIPLES.map((p,i)=>`<article class="prcard"><div class="prpic">${LP[p.k]}</div><span class="tag">${String(i+1).padStart(2,"0")}</span><h3>${p.t}</h3><p>${p.d}</p><p class="prhow"><b>طبّقه:</b> ${p.how}</p><div class="vids">${p.src.map(([t,h])=>`<a href="${h}" target="_blank" rel="noopener">${t}</a>`).join("")}</div></article>`).join("")}</div>
  <div class="uh" style="margin-top:40px"><span class="tag">كل التريكات</span><h2>${tricks.length} تريك من كل الدروس</h2><p>دوّر على أي إشي: «بار»، «خنصر»، «إيقاع»…</p></div>
  <input type="search" class="csearch tsearch" placeholder="دوّر بالتريكات…" aria-label="دوّر بالتريكات" style="width:100%">
  <div class="trlist">${tricks.map(({l,t})=>`<a class="tritem" href="#/l/${l.id}" data-s="${(t+" "+l.t).toLowerCase()}"><span class="tag">درس ${l.no}</span><b>${l.t}</b><span>${t}</span></a>`).join("")}</div>${FOOT}`;
  const items=[...view.querySelectorAll(".tritem")];
  view.querySelector(".tsearch").oninput=e=>{const q=e.target.value.trim().toLowerCase();items.forEach(a=>a.hidden=q&&!a.dataset.s.includes(q))};
}
